import sys
sjoiafjwrfoiajweoifnw9uvbawoufjawoeifjawoirfjaorngvaournvoaijrfoaiwrjfoaiwr = []

sjoiafjwrfoiajweoifnw9uvbawoufjawoeifjawoirfjaorngvaournvoaijrfoaiwrjfoaiwr.append(chr(0b01001000))
sjoiafjwrfoiajweoifnw9uvbawoufjawoeifjawoirfjaorngvaournvoaijrfoaiwrjfoaiwr.append(chr(0b01100001))
sjoiafjwrfoiajweoifnw9uvbawoufjawoeifjawoirfjaorngvaournvoaijrfoaiwrjfoaiwr.append(chr(0b01110000))


sjoiafjwrfoiajweoifnw9uvbawoufjawoeifjawoirfjaorngvaournvoaijrfoaiwrjfoaiwr.append(chr(0b01110000))
sjoiafjwrfoiajweoifnw9uvbawoufjawoeifjawoirfjaorngvaournvoaijrfoaiwrjfoaiwr.append(chr(0b01111001))




sjoiafjwrfoiajweoifnw9uvbawoufjawoeifjawoirfjaorngvaournvoaijrfoaiwrjfoaiwr.append(chr(0b00100000))
sjoiafjwrfoiajweoifnw9uvbawoufjawoeifjawoirfjaorngvaournvoaijrfoaiwrjfoaiwr.append(chr(0b01100010))
sjoiafjwrfoiajweoifnw9uvbawoufjawoeifjawoirfjaorngvaournvoaijrfoaiwrjfoaiwr.append(chr(0b01101001))
sjoiafjwrfoiajweoifnw9uvbawoufjawoeifjawoirfjaorngvaournvoaijrfoaiwrjfoaiwr.append(chr(0b01110100))







sjoiafjwrfoiajweoifnw9uvbawoufjawoeifjawoirfjaorngvaournvoaijrfoaiwrjfoaiwr.append(chr(0b01101000))
sjoiafjwrfoiajweoifnw9uvbawoufjawoeifjawoirfjaorngvaournvoaijrfoaiwrjfoaiwr.append(chr(0b01100100))
sjoiafjwrfoiajweoifnw9uvbawoufjawoeifjawoirfjaorngvaournvoaijrfoaiwrjfoaiwr.append(chr(0b01100001))
sjoiafjwrfoiajweoifnw9uvbawoufjawoeifjawoirfjaorngvaournvoaijrfoaiwrjfoaiwr.append(chr(0b01111001))
sjoiafjwrfoiajweoifnw9uvbawoufjawoeifjawoirfjaorngvaournvoaijrfoaiwrjfoaiwr.append(chr(0b00100000))
sjoiafjwrfoiajweoifnw9uvbawoufjawoeifjawoirfjaorngvaournvoaijrfoaiwrjfoaiwr.append(chr(0b01010100))
sjoiafjwrfoiajweoifnw9uvbawoufjawoeifjawoirfjaorngvaournvoaijrfoaiwrjfoaiwr.append(chr(0b01110010))
sjoiafjwrfoiajweoifnw9uvbawoufjawoeifjawoirfjaorngvaournvoaijrfoaiwrjfoaiwr.append(chr(0b01100101))
sjoiafjwrfoiajweoifnw9uvbawoufjawoeifjawoirfjaorngvaournvoaijrfoaiwrjfoaiwr.append(chr(0b01101110))
sjoiafjwrfoiajweoifnw9uvbawoufjawoeifjawoirfjaorngvaournvoaijrfoaiwrjfoaiwr.append(chr(0b01110100))
sjoiafjwrfoiajweoifnw9uvbawoufjawoeifjawoirfjaorngvaournvoaijrfoaiwrjfoaiwr.append(chr(0b01101111))
sjoiafjwrfoiajweoifnw9uvbawoufjawoeifjawoirfjaorngvaournvoaijrfoaiwrjfoaiwr.append(chr(0b01101110))

jofaijweofiajweofiajwhrgoibaw9ufvbowurfnoqiwejfoaiwghoiwrjfoqiwejfoiawejfwq = ""

jofaijweofiajweofiajwhrgoibaw9ufvbowurfnoqiwejfoaiwghoiwrjfoqiwejfoiawejfwq = jofaijweofiajweofiajwhrgoibaw9ufvbowurfnoqiwejfoaiwghoiwrjfoqiwejfoiawejfwq + sjoiafjwrfoiajweoifnw9uvbawoufjawoeifjawoirfjaorngvaournvoaijrfoaiwrjfoaiwr[0]
jofaijweofiajweofiajwhrgoibaw9ufvbowurfnoqiwejfoaiwghoiwrjfoqiwejfoiawejfwq = jofaijweofiajweofiajwhrgoibaw9ufvbowurfnoqiwejfoaiwghoiwrjfoqiwejfoiawejfwq + sjoiafjwrfoiajweoifnw9uvbawoufjawoeifjawoirfjaorngvaournvoaijrfoaiwrjfoaiwr[1]
jofaijweofiajweofiajwhrgoibaw9ufvbowurfnoqiwejfoaiwghoiwrjfoqiwejfoiawejfwq = jofaijweofiajweofiajwhrgoibaw9ufvbowurfnoqiwejfoaiwghoiwrjfoqiwejfoiawejfwq + sjoiafjwrfoiajweoifnw9uvbawoufjawoeifjawoirfjaorngvaournvoaijrfoaiwrjfoaiwr[2]
jofaijweofiajweofiajwhrgoibaw9ufvbowurfnoqiwejfoaiwghoiwrjfoqiwejfoiawejfwq = jofaijweofiajweofiajwhrgoibaw9ufvbowurfnoqiwejfoaiwghoiwrjfoqiwejfoiawejfwq + sjoiafjwrfoiajweoifnw9uvbawoufjawoeifjawoirfjaorngvaournvoaijrfoaiwrjfoaiwr[3]
jofaijweofiajweofiajwhrgoibaw9ufvbowurfnoqiwejfoaiwghoiwrjfoqiwejfoiawejfwq = jofaijweofiajweofiajwhrgoibaw9ufvbowurfnoqiwejfoaiwghoiwrjfoqiwejfoiawejfwq + sjoiafjwrfoiajweoifnw9uvbawoufjawoeifjawoirfjaorngvaournvoaijrfoaiwrjfoaiwr[4]
jofaijweofiajweofiajwhrgoibaw9ufvbowurfnoqiwejfoaiwghoiwrjfoqiwejfoiawejfwq = jofaijweofiajweofiajwhrgoibaw9ufvbowurfnoqiwejfoaiwghoiwrjfoqiwejfoiawejfwq + sjoiafjwrfoiajweoifnw9uvbawoufjawoeifjawoirfjaorngvaournvoaijrfoaiwrjfoaiwr[5]
jofaijweofiajweofiajwhrgoibaw9ufvbowurfnoqiwejfoaiwghoiwrjfoqiwejfoiawejfwq = jofaijweofiajweofiajwhrgoibaw9ufvbowurfnoqiwejfoaiwghoiwrjfoqiwejfoiawejfwq + sjoiafjwrfoiajweoifnw9uvbawoufjawoeifjawoirfjaorngvaournvoaijrfoaiwrjfoaiwr[6]
jofaijweofiajweofiajwhrgoibaw9ufvbowurfnoqiwejfoaiwghoiwrjfoqiwejfoiawejfwq = jofaijweofiajweofiajwhrgoibaw9ufvbowurfnoqiwejfoaiwghoiwrjfoqiwejfoiawejfwq + sjoiafjwrfoiajweoifnw9uvbawoufjawoeifjawoirfjaorngvaournvoaijrfoaiwrjfoaiwr[7]
jofaijweofiajweofiajwhrgoibaw9ufvbowurfnoqiwejfoaiwghoiwrjfoqiwejfoiawejfwq = jofaijweofiajweofiajwhrgoibaw9ufvbowurfnoqiwejfoaiwghoiwrjfoqiwejfoiawejfwq + sjoiafjwrfoiajweoifnw9uvbawoufjawoeifjawoirfjaorngvaournvoaijrfoaiwrjfoaiwr[8]
jofaijweofiajweofiajwhrgoibaw9ufvbowurfnoqiwejfoaiwghoiwrjfoqiwejfoiawejfwq = jofaijweofiajweofiajwhrgoibaw9ufvbowurfnoqiwejfoaiwghoiwrjfoqiwejfoiawejfwq + sjoiafjwrfoiajweoifnw9uvbawoufjawoeifjawoirfjaorngvaournvoaijrfoaiwrjfoaiwr[9]
jofaijweofiajweofiajwhrgoibaw9ufvbowurfnoqiwejfoaiwghoiwrjfoqiwejfoiawejfwq = jofaijweofiajweofiajwhrgoibaw9ufvbowurfnoqiwejfoaiwghoiwrjfoqiwejfoiawejfwq + sjoiafjwrfoiajweoifnw9uvbawoufjawoeifjawoirfjaorngvaournvoaijrfoaiwrjfoaiwr[10]
jofaijweofiajweofiajwhrgoibaw9ufvbowurfnoqiwejfoaiwghoiwrjfoqiwejfoiawejfwq = jofaijweofiajweofiajwhrgoibaw9ufvbowurfnoqiwejfoaiwghoiwrjfoqiwejfoiawejfwq + sjoiafjwrfoiajweoifnw9uvbawoufjawoeifjawoirfjaorngvaournvoaijrfoaiwrjfoaiwr[11]
jofaijweofiajweofiajwhrgoibaw9ufvbowurfnoqiwejfoaiwghoiwrjfoqiwejfoiawejfwq = jofaijweofiajweofiajwhrgoibaw9ufvbowurfnoqiwejfoaiwghoiwrjfoqiwejfoiawejfwq + sjoiafjwrfoiajweoifnw9uvbawoufjawoeifjawoirfjaorngvaournvoaijrfoaiwrjfoaiwr[12]
jofaijweofiajweofiajwhrgoibaw9ufvbowurfnoqiwejfoaiwghoiwrjfoqiwejfoiawejfwq = jofaijweofiajweofiajwhrgoibaw9ufvbowurfnoqiwejfoaiwghoiwrjfoqiwejfoiawejfwq + sjoiafjwrfoiajweoifnw9uvbawoufjawoeifjawoirfjaorngvaournvoaijrfoaiwrjfoaiwr[13]
jofaijweofiajweofiajwhrgoibaw9ufvbowurfnoqiwejfoaiwghoiwrjfoqiwejfoiawejfwq = jofaijweofiajweofiajwhrgoibaw9ufvbowurfnoqiwejfoaiwghoiwrjfoqiwejfoiawejfwq + sjoiafjwrfoiajweoifnw9uvbawoufjawoeifjawoirfjaorngvaournvoaijrfoaiwrjfoaiwr[14]
jofaijweofiajweofiajwhrgoibaw9ufvbowurfnoqiwejfoaiwghoiwrjfoqiwejfoiawejfwq = jofaijweofiajweofiajwhrgoibaw9ufvbowurfnoqiwejfoaiwghoiwrjfoqiwejfoiawejfwq + sjoiafjwrfoiajweoifnw9uvbawoufjawoeifjawoirfjaorngvaournvoaijrfoaiwrjfoaiwr[15]
jofaijweofiajweofiajwhrgoibaw9ufvbowurfnoqiwejfoaiwghoiwrjfoqiwejfoiawejfwq = jofaijweofiajweofiajwhrgoibaw9ufvbowurfnoqiwejfoaiwghoiwrjfoqiwejfoiawejfwq + sjoiafjwrfoiajweoifnw9uvbawoufjawoeifjawoirfjaorngvaournvoaijrfoaiwrjfoaiwr[16]
jofaijweofiajweofiajwhrgoibaw9ufvbowurfnoqiwejfoaiwghoiwrjfoqiwejfoiawejfwq = jofaijweofiajweofiajwhrgoibaw9ufvbowurfnoqiwejfoaiwghoiwrjfoqiwejfoiawejfwq + sjoiafjwrfoiajweoifnw9uvbawoufjawoeifjawoirfjaorngvaournvoaijrfoaiwrjfoaiwr[17]
jofaijweofiajweofiajwhrgoibaw9ufvbowurfnoqiwejfoaiwghoiwrjfoqiwejfoiawejfwq = jofaijweofiajweofiajwhrgoibaw9ufvbowurfnoqiwejfoaiwghoiwrjfoqiwejfoiawejfwq + sjoiafjwrfoiajweoifnw9uvbawoufjawoeifjawoirfjaorngvaournvoaijrfoaiwrjfoaiwr[18]
jofaijweofiajweofiajwhrgoibaw9ufvbowurfnoqiwejfoaiwghoiwrjfoqiwejfoiawejfwq = jofaijweofiajweofiajwhrgoibaw9ufvbowurfnoqiwejfoaiwghoiwrjfoqiwejfoiawejfwq + sjoiafjwrfoiajweoifnw9uvbawoufjawoeifjawoirfjaorngvaournvoaijrfoaiwrjfoaiwr[19]
jofaijweofiajweofiajwhrgoibaw9ufvbowurfnoqiwejfoaiwghoiwrjfoqiwejfoiawejfwq = jofaijweofiajweofiajwhrgoibaw9ufvbowurfnoqiwejfoaiwghoiwrjfoqiwejfoiawejfwq + sjoiafjwrfoiajweoifnw9uvbawoufjawoeifjawoirfjaorngvaournvoaijrfoaiwrjfoaiwr[20]

print(jofaijweofiajweofiajwhrgoibaw9ufvbowurfnoqiwejfoaiwghoiwrjfoqiwejfoiawejfwq, file=sys.stdout, sep="4kjfqoqwiejfqw0iefja0ew814yrt10")
